const ovp = "#OVP."
const exp ="#VIPEXPRESSO."
const approve = "Cliente confirmou ter realizado a compra.\nAprovado.";
const website = "Cliente confirmou ter realizado a compra pelo site.\n\nAprovado."
const app = "Cliente confirmou ter realizado a compra pelo Aplicativo.\n\nAprovado."
const outros ="Cliente confirmou ter realizado a compra por meio do canal de vendas intermediário ***.\nCliente informou corretamente os três últimos dígitos do cartão e e-mail.\n\nAprovado."
const fraude = "Cliente não reconhece a compra.\nInforma não ter autorizado terceiros a efetuarem compras em seu nome.\nConfirma nome completo e data de nascimento.\n\nFraude confirmada.";
const fraude2 = "Cliente não reconhece a compra.\nInforma não ter autorizado terceiros a efetuarem compras em seu nome.\nConfirma nome completo mas se recusa a confirmar data de nascimento.\n\nFraude confirmada.";
const cancel = "Titular do pedido não deseja prosseguir com a compra.\nConfirma nome completo e data de nascimento.\n\nCancelado."
